---
- name: Check if Firefox is installed
  ansible.builtin.command: dnf list installed firefox
  register: firefox_check
  ignore_errors: yes

- name: Install Firefox if not installed
  dnf:
    name: firefox
    state: present
  when: firefox_check.rc != 0

- name: Create Firefox profiles
  become: yes
  become_user: "{{ user }}"
  command: firefox --no-remote -CreateProfile "{{ item }}"
  loop: "{{ profile_names }}"
  when: firefox_check.rc == 0

- name: Download and install Firefox GNOME theme
  become: yes
  shell: curl -s -o- https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install-by-curl.sh | bash
  when: firefox_check.rc == 0
