---
- name: Install Flatpak apps
  hosts: localhost
  become: yes
  roles:
    - install-flatpak-apps

- name: Install autenticaçãoGov
  hosts: localhost
  become: yes
  roles:
    - install-autGov

# Fedora packages
- name: Install Speedtest
  hosts: localhost
  become: yes
  roles:
    - install-speedtest-cli

- name: Install scrcpy
  hosts: localhost
  become: yes
  roles:
    - install-scr-cpy

- name: Install Python
  hosts: localhost
  become: yes
  roles:
    - install-python