---

- name: Check if using Fedora
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check distribution
      ansible.builtin.shell:
        cmd: cat /etc/os-release | grep -E '^NAME=|^VERSION='
      register: os_release
      changed_when: false  # Since this is a read-only task, we mark it as unchanged

    - name: Print distribution details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ os_release.stdout_lines }}"

    - name: Abort if not Fedora
      fail:
        msg: "This playbook is only intended for Fedora"
      when: '"Fedora" not in os_release.stdout'

# Fedora

- name: Update all dnf packages
  hosts: localhost
  become: yes
  tasks:
    - name: Update dnf packages
      dnf:
        name: '*'
        state: latest

- name: Install Speedtest
  hosts: localhost
  become: yes
  roles:
    - speedtest-cli

- name: Install scrcpy
  hosts: localhost
  become: yes
  roles:
    - scr-cpy

- name: Configure Firefox
  hosts: localhost
  become: yes
  roles:
    - firefox
  vars:
      user: admin
      # profile_names:
      #  - custom1
      #  - custom2

# Gnome
- name: Configure Gnome
  hosts: localhost
  become: true
  roles:
    - gnome
  vars:
    user: admin

# Flatpaks
- name: Install Flatpaks
  hosts: localhost
  become: true
  roles:
    - flatpak-apps

- name: Install autenticaçãoGov
  hosts: localhost
  become: yes
  roles:
    - autGov


# Development

- name: Install Docker
  hosts: localhost
  become: true
  roles:
    - docker

- name: Install Python
  hosts: localhost
  become: yes
  roles:
    - python

- name: Install NodeJS
  hosts: localhost
  become: yes
  roles:
    - nodejs

- name: Install VirtualBox
  hosts: localhost
  become: true
  roles:
    - virtual-box 

- name: Install RabbitMQ
  hosts: localhost
  become: true
  roles:
    - rabbitmq
