---

- name: Check if using Fedora
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check distribution
      ansible.builtin.shell:
        cmd: cat /etc/os-release | grep -E '^NAME=|^VERSION='
      register: os_release

    - name: Print distribution details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ os_release.stdout_lines }}"

    - name: Abort if not Fedora
      fail:
        msg: "This playbook is only intended for Fedora"
      when: '"Fedora" not in os_release.stdout'

# Fedora
- name: Handle dnf packages
  hosts: localhost
  become: yes
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Remove packages
      dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - libreoffice*

    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - fastfetch
        - pandoc
        - pandoc-pdf
        - keepassxc

# Development
- name: Install Development Tools
  hosts: localhost
  become: true
  roles:
#    - lamp
    - docker
    - python
    - nodejs
    - rabbitmq


# Gnome
- name: Configure Gnome
  hosts: localhost
  become: true
  roles:
    - gnome
  vars:
    user: admin
    #hostname_static: fedora-pc
    #hostname_pretty: Fedora PC

# Gnome
- name: Install Gnome Extensions
  hosts: localhost
  become: true
  become_user: admin
  roles:
    - gnome-extensions
  vars:
    gnome_extension_ids:
    #  - 36    # lock keys
    #  - 97    # coverflow alt tab
    #  - 307   # dash to dock
      - 517   # caffeine
    #  - 615   # tray icons
    #  - 1319  # GS connect
    #  - 1460  # vitals
    #  - 1804  # service monitor
    #  - 2992  # IdeaPad
    #  - 3193  # blur my shel
    #  - 3628  # arcmenu
    #  - 3733  # tiling assistant
    #  - 3843  # just perfection
    #  - 4470  # media controls
    #  - 5278  # Pano clipboard manager
    #  - 5660  # weather or not
    #  - 5724  # battery health charging
      - 6406  # fedora update indicator

# Firefox
- name: Configure Firefox
  hosts: localhost
  become: yes
  roles:
    - firefox
  vars:
      user: admin
      # profile_names:
      #  - custom1
      #  - custom2

# Flatpaks
- name: Install Flatpak Apps
  hosts: localhost
  become: true
  roles:
    - flatpak-apps
    - autGov

# Applications
- name: Install Applications
  hosts: localhost
  become: true
  roles:
    - scr-cpy
    - speedtest-cli
    - virtual-box 
    - jetbrains-toolbox
    - vscode


