---
- name: Install Flatpaks
  hosts: localhost
  become: true
  roles:
    - flatpak-apps

- name: Install autenticaçãoGov
  hosts: localhost
  become: yes
  roles:
    - autGov

- name: Install Speedtest
  hosts: localhost
  become: yes
  roles:
    - speedtest-cli

- name: Install scrcpy
  hosts: localhost
  become: yes
  roles:
    - scr-cpy

- name: Install Python
  hosts: localhost
  become: yes
  roles:
    - python

- name: Install NodeJS
  hosts: localhost
  become: yes
  roles:
    - nodejs

- name: Install VirtualBox
  hosts: localhost
  become: true
  roles:
    - install-virtual-box 

- name: Install Docker
  hosts: localhost
  become: true
  roles:
    - docker
