---

- name: Check if using Fedora
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check distribution
      ansible.builtin.shell:
        cmd: cat /etc/os-release | grep -E '^NAME=|^VERSION='
      register: os_release

    - name: Print distribution details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ os_release.stdout_lines }}"

    - name: Abort if not Fedora
      fail:
        msg: "This playbook is only intended for Fedora"
      when: '"Fedora" not in os_release.stdout'

# Fedora
- name: Handle dnf packages
  hosts: localhost
  become: yes
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Remove packages
      dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - libreoffice*

    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - fastfetch
        - pandoc
        - pandoc-pdf
        - keepassxc

# Development
- name: Install Development Tools
  hosts: localhost
  become: true
  roles:
    - lamp
    - docker
    - python
    - nodejs
    - rabbitmq

# Gnome
- name: Configure Gnome
  hosts: localhost
  become: true
  roles:
    - gnome
  vars:
    user: admin
    #hostname_static: fedora-pc
    #hostname_pretty: Fedora PC

# Gnome
- name: Install Gnome Extensions
  hosts: localhost
  become: true
  become_user: admin
  roles:
    - gnome-extensions

# Firefox
- name: Configure Firefox
  hosts: localhost
  become: yes
  roles:
    - firefox
  vars:
      user: admin
      # profile_names:
      #  - custom1
      #  - custom2

# Flatpaks
- name: Install Flatpak Apps
  hosts: localhost
  become: true
  roles:
    - flatpak-apps
    - autGov

# Applications
- name: Install Applications
  hosts: localhost
  become: true
  roles:
    - scr-cpy
    - speedtest-cli
    - virtual-box 
    - jetbrains-toolbox
    - vscode
    - kathara
  vars:
    user: admin
