---
- name: Install Flatpaks
  hosts: localhost
  become: true
  roles:
    - install-flatpak-apps

- name: Install autenticaçãoGov
  hosts: localhost
  become: yes
  roles:
    - install-autGov

- name: Install Speedtest
  hosts: localhost
  become: yes
  roles:
    - install-speedtest-cli

- name: Install scrcpy
  hosts: localhost
  become: yes
  roles:
    - install-scr-cpy

- name: Install Python
  hosts: localhost
  become: yes
  roles:
    - install-python

- name: Install VirtualBox
  hosts: localhost
  become: true
  roles:
    - install-virtual-box 

- name: Install RabbitMQ
  hosts: localhost
  become: yes
  roles:
    - rabbitmq

- name: Install Docker
  hosts: localhost
  become: true
  roles:
    - docker

- name: Configure Gnome
  hosts: localhost
  become: true
  roles:
    - gnome

