---
- name: Import VirtualBox GPG Key
  rpm_key:
    key: "{{ virtualbox_gpg_key_url }}"

- name: Download VirtualBox RPM
  get_url:
    url: "{{ virtualbox_url }}"
    dest: "{{ download_dir }}/VirtualBox-{{ virtualbox_version }}.rpm"

- name: Install dependencies
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ virtualbox_dep_pkgs }}"

- name: Install VirtualBox
  dnf:
    name: "{{ download_dir }}/VirtualBox-{{ virtualbox_version }}.rpm"
    state: present
