- name: Check if flatpak is installed
  shell: flatpak list --app | grep pt.gov.autenticaca
  ignore_errors: true 
  register: flatpak_check
  
- name: Download and Install flatpak
  become: yes
  block:
    - name: Download flatpak
      get_url:
        url: https://aplicacoes.autenticacao.gov.pt/apps/pteid-mw-linux.x86_64.flatpak
        dest: /tmp/pteid-mw-linux.x86_64.flatpak

    - name: Install flatpak
      shell:
        cmd: flatpak install -y /tmp/pteid-mw-linux.x86_64.flatpak
      args:
        chdir: /tmp

    - name: Delete flatpak file
      file:
        path: /tmp/pteid-mw-linux.x86_64.flatpak
        state: absent
  when: flatpak_check.rc != 0  

